export enum WsErrorCodes {
	ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
	ROOM_EXISTS = "ROOM_EXISTS",
	ALREADY_IN_ROOM = "ALREADY_IN_ROOM",
	NOT_IN_ROOM = "NOT_IN_ROOM",
	MEMBERS_NOT_FOUND = "MEMBERS_NOT_FOUND",
	INVALID_PAYLOAD = "INVALID_PAYLOAD",
	RATE_LIMITED = "RATE_LIMITED",
	MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG",
	HEARTBEAT_TIMEOUT = "HEARTBEAT_TIMEOUT",
	UNAUTHORIZED = "UNAUTHORIZED",
}
